[quiz]
title = "Sample Quiz"
points = 10

[[quiz.questions]]
question_type = "single_choice"
question = "What is the capital of France?"
options = ["Paris", "London", "Madrid", "Berlin"]
answer = [0]
explanations = ["Correct!", "Incorrect", "Incorrect", "Incorrect"]
points = 5

[[quiz.questions]]
question_type = "single_choice"
question = "What is the highest mountain in the world?"
options = ["K2", "Denali", "Mount Everest", "Kilimanjaro"]
answer = [2]
explanations = ["Incorrect", "Incorrect", "Correct!", "Incorrect"]
points = 5

[[quiz.questions]]
question_type = "multi_choice"
question = "Which of the following are countries in South America?"
options = ["Brazil", "Russia", "Peru", "India", "China", "Chile"]
answer = [0, 2, 5]
explanations = ["Brazil is in South America", "Peru is in South America", "Chile is in South America", "India is not in South America", "China is not in South America", "Russia is not in South America"]
points = 10